### ISSUE TITLE
Castling is not well reported by lichess.

### ISSUE THREAD

**Issue by amullarney** [xtuml/chess#4]
The 'moves' array appears to report the movement of the King but not the simultaneous movement of the Rook in a 'Castle' move.

**Comment by leviathan747** [comment]
This is normal. If the king moves two squares, you can infer the movement of the corresponding rook based on the rules of the game. Note that the notation used is not specific to lichess, but is a standardized format https://www.chessprogramming.org/Algebraic_Chess_Notation#Pure_coordinate_notation
